export enum ExchangeStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ITEM_RECEIVED = 'ITEM_RECEIVED',
  REPLACEMENT_SHIPPED = 'REPLACEMENT_SHIPPED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
