export enum NotificationType {
  ORDER_UPDATE = 'ORDER_UPDATE',
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  DELIVERY_UPDATE = 'DELIVERY_UPDATE',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
  WALLET = 'WALLET',
  LOYALTY = 'LOYALTY',
  REVIEW = 'REVIEW',
  SUPPORT = 'SUPPORT',
  REFERRAL = 'REFERRAL',
}
