export enum PaymentMethod {
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  STRIPE = 'STRIPE',
  PAYMOB = 'PAYMOB',
  FAWRY = 'FAWRY',
  WALLET = 'WALLET',
  BANK_TRANSFER = 'BANK_TRANSFER',
}
