FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

RUN addgroup -g 1001 -S pharmaworld && \
    adduser -S pharmaworld -u 1001 -G pharmaworld

USER pharmaworld

EXPOSE 3000

CMD ["node", "dist/main.js"]
