import 'package:flutter/material.dart';
import 'dart:async';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'PharmaWorld Super Admin',
      'login': 'Login',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'mfaCode': 'MFA Code',
      'verify': 'Verify',
      'dashboard': 'Dashboard',
      'pharmacies': 'Pharmacies',
      'users': 'Users',
      'roles': 'Roles & Permissions',
      'systemHealth': 'System Health',
      'featureFlags': 'Feature Flags',
      'maintenance': 'Maintenance',
      'config': 'Configuration',
      'auditLogs': 'Audit Logs',
      'analytics': 'Analytics',
      'reports': 'Reports',
      'settings': 'Settings',
      'search': 'Search',
      'filter': 'Filter',
      'export': 'Export',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'view': 'View',
      'close': 'Close',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'noData': 'No data available',
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'totalRevenue': 'Total Revenue',
      'totalOrders': 'Total Orders',
      'totalUsers': 'Total Users',
      'totalMedicines': 'Total Medicines',
      'totalPharmacies': 'Total Pharmacies',
      'activeDrivers': 'Active Drivers',
      'systemAlerts': 'System Alerts',
      'realtimeOrderFlow': 'Real-time Order Flow',
      'revenueTrends': 'Revenue Trends',
      'ordersByRegion': 'Orders by Region',
      'topPharmacies': 'Top Pharmacies',
      'enable': 'Enable',
      'disable': 'Disable',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'suspended': 'Suspended',
      'active': 'Active',
      'inactive': 'Inactive',
      'maintenanceMode': 'Maintenance Mode',
      'startMaintenance': 'Start Maintenance',
      'endMaintenance': 'End Maintenance',
      'featureFlagName': 'Feature Flag Name',
      'rolloutPercentage': 'Rollout Percentage',
      'permissionMatrix': 'Permission Matrix',
      'createRole': 'Create Role',
      'editRole': 'Edit Role',
      'deleteRole': 'Delete Role',
      'roleName': 'Role Name',
      'roleDescription': 'Role Description',
      'assignRole': 'Assign Role',
      'suspendUser': 'Suspend User',
      'activateUser': 'Activate User',
      'apiResponseTimes': 'API Response Times',
      'errorRates': 'Error Rates',
      'databaseHealth': 'Database Health',
      'cacheHitRates': 'Cache Hit Rates',
      'activeSessions': 'Active Sessions',
      'serverResourceUsage': 'Server Resource Usage',
      'environmentSettings': 'Environment Settings',
      'paymentGateway': 'Payment Gateway',
      'deliverySettings': 'Delivery Settings',
      'emailSMSSettings': 'Email/SMS Settings',
      'storageSettings': 'Storage Settings',
      'cacheSettings': 'Cache Settings',
      'filterByUser': 'Filter by User',
      'filterByAction': 'Filter by Action',
      'filterByEntity': 'Filter by Entity',
      'filterByDateRange': 'Filter by Date Range',
      'exportAuditLogs': 'Export Audit Logs',
      'securityAlerts': 'Security Alerts',
      'crossBranchAnalytics': 'Cross-Branch Analytics',
      'revenueComparison': 'Revenue Comparison',
      'userGrowth': 'User Growth',
      'medicinePopularity': 'Medicine Popularity',
      'geographicDistribution': 'Geographic Distribution',
      'generateReport': 'Generate Report',
      'comparePeriods': 'Compare Periods',
      'exportToPDF': 'Export to PDF',
      'exportToExcel': 'Export to Excel',
      'branchPerformance': 'Branch Performance',
      'branchDetails': 'Branch Details',
      'systemOverview': 'System Overview',
      'userManagement': 'User Management',
      'contentManagement': 'Content Management',
      'operations': 'Operations',
      'analyticsSection': 'Analytics',
      'security': 'Security',
      'configuration': 'Configuration',
      'welcomeBack': 'Welcome back',
      'loginSubtitle': 'Sign in to PharmaWorld Super Admin',
      'enterMfaCode': 'Enter your 6-digit MFA code',
      'superAdminLogin': 'Super Admin Login',
      'rememberMe': 'Remember me',
      'forgotPassword': 'Forgot password?',
      'totalRevenueAcross': 'Total Revenue Across All Pharmacies',
      'ordersSystemWide': 'Total Orders System-wide',
      'allSystemUsers': 'All Users (Customers, Drivers, Admins)',
      'medicineListings': 'Medicine Listings',
      'systemHealthStatus': 'System Health Status',
      'apiStatus': 'API Status',
      'databaseStatus': 'Database Status',
      'cacheStatus': 'Cache Status',
      'healthy': 'Healthy',
      'degraded': 'Degraded',
      'down': 'Down',
      'normal': 'Normal',
      'high': 'High',
      'critical': 'Critical',
      'yes': 'Yes',
      'no': 'No',
      'all': 'All',
      'activeFlag': 'Active',
      'inactiveFlag': 'Inactive',
      'addNew': 'Add New',
      'rollout': 'Rollout',
      'targetedRoles': 'Targeted Roles',
      'targetedUsers': 'Targeted Users',
      'abTesting': 'A/B Testing',
      'maintenanceMessage': 'Maintenance Message',
      'whitelistIPs': 'Whitelist IPs',
      'whitelistUsers': 'Whitelist Users',
      'scheduledWindow': 'Scheduled Window',
      'currentStatus': 'Current Status',
      'permission': 'Permission',
      'noRolesDefined': 'No roles defined yet',
      'createCustomRole': 'Create custom role',
      'assignPermissions': 'Assign permissions',
      'actions': 'Actions',
      'role': 'Role',
      'lastActive': 'Last Active',
      'dateJoined': 'Date Joined',
      'userDetail': 'User Detail',
      'fullHistory': 'Full History',
      'responseTime': 'Response Time',
      'uptime': 'Uptime',
      'errorRate': 'Error Rate',
      'requestsPerSecond': 'Requests/Second',
      'cpuUsage': 'CPU Usage',
      'memoryUsage': 'Memory Usage',
      'diskUsage': 'Disk Usage',
      'connectionPool': 'Connection Pool',
      'activeConnections': 'Active Connections',
      'hitRate': 'Hit Rate',
      'missRate': 'Miss Rate',
      'totalKeys': 'Total Keys',
      'memoryConsumed': 'Memory Consumed',
      'onlineSessions': 'Online Sessions',
      'peakToday': 'Peak Today',
      'avgDuration': 'Avg Duration',
      'env': 'Environment',
      'region': 'Region',
      'apiEndpoint': 'API Endpoint',
      'debugMode': 'Debug Mode',
      'maxUploadSize': 'Max Upload Size',
      'currency': 'Currency',
      'taxRate': 'Tax Rate',
      'deliveryRadius': 'Delivery Radius',
      'maxDeliveryDistance': 'Max Delivery Distance',
      'driverCommission': 'Driver Commission',
      'smtpHost': 'SMTP Host',
      'smtpPort': 'SMTP Port',
      'senderEmail': 'Sender Email',
      'smsProvider': 'SMS Provider',
      'firebaseConfig': 'Firebase Config',
      'storageProvider': 'Storage Provider',
      'maxFileSize': 'Max File Size',
      'allowedFormats': 'Allowed Formats',
      'driverTTL': 'Driver TTL',
      'orderCacheTTL': 'Order Cache TTL',
      'user': 'User',
      'action': 'Action',
      'entity': 'Entity',
      'timestamp': 'Timestamp',
      'details': 'Details',
      'noAuditLogs': 'No audit logs found',
      'period': 'Period',
      'revenueByPharmacy': 'Revenue by Pharmacy',
      'ordersByCity': 'Orders by City',
      'newUsersOverTime': 'New Users Over Time',
      'usersByRole': 'Users by Role',
      'mostOrderedMedicines': 'Most Ordered Medicines',
      'ordersByMedicineType': 'Orders by Medicine Type',
      'heatmapData': 'Geographic Heatmap',
      'ordersByLocation': 'Orders by Location',
      'reportType': 'Report Type',
      'dateRange': 'Date Range',
      'startDate': 'Start Date',
      'endDate': 'End Date',
      'comparisonPeriod': 'Comparison Period',
      'downloadReport': 'Download Report',
      'branch': 'Branch',
      'performance': 'Performance',
      'comparisons': 'Comparisons',
    },
    'ar': {
      'appName': 'فارما وورلد الأدمن الأعلى',
      'login': 'تسجيل الدخول',
      'logout': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'mfaCode': 'رمز التحقق',
      'verify': 'تحقق',
      'dashboard': 'لوحة التحكم',
      'pharmacies': 'الصيدليات',
      'users': 'المستخدمين',
      'roles': 'الأدوار والصلاحيات',
      'systemHealth': 'صحة النظام',
      'featureFlags': 'مميزات النظام',
      'maintenance': 'الصيانة',
      'config': 'الإعدادات',
      'auditLogs': 'سجلات المراجعة',
      'analytics': 'التحليلات',
      'reports': 'التقارير',
      'settings': 'الإعدادات',
      'search': 'بحث',
      'filter': 'تصفية',
      'export': 'تصدير',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'view': 'عرض',
      'close': 'إغلاق',
      'confirm': 'تأكيد',
      'loading': 'جاري التحميل...',
      'noData': 'لا توجد بيانات',
      'success': 'نجاح',
      'error': 'خطأ',
      'warning': 'تحذير',
      'totalRevenue': 'إجمالي الإيرادات',
      'totalOrders': 'إجمالي الطلبات',
      'totalUsers': 'إجمالي المستخدمين',
      'totalMedicines': 'إجمالي الأدوية',
      'totalPharmacies': 'إجمالي الصيدليات',
      'activeDrivers': 'السائقون النشطون',
      'systemAlerts': 'تنبيهات النظام',
      'realtimeOrderFlow': 'تدفق الطلبات المباشر',
      'revenueTrends': 'اتجاهات الإيرادات',
      'ordersByRegion': 'الطلبات حسب المنطقة',
      'topPharmacies': 'أفضل الصيدليات',
      'enable': 'تفعيل',
      'disable': 'تعطيل',
      'enabled': 'مفعل',
      'disabled': 'معطل',
      'suspended': 'معلق',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'maintenanceMode': 'وضع الصيانة',
      'startMaintenance': 'بدء الصيانة',
      'endMaintenance': 'إنهاء الصيانة',
      'featureFlagName': 'اسم الميزة',
      'rolloutPercentage': 'نسبة النشر',
      'permissionMatrix': 'مصفوفة الصلاحيات',
      'createRole': 'إنشاء دور',
      'editRole': 'تعديل الدور',
      'deleteRole': 'حذف الدور',
      'roleName': 'اسم الدور',
      'roleDescription': 'وصف الدور',
      'assignRole': 'تعيين الدور',
      'suspendUser': 'تعليق المستخدم',
      'activateUser': 'تفعيل المستخدم',
      'apiResponseTimes': 'أوقات استجابة API',
      'errorRates': 'معدلات الخطأ',
      'databaseHealth': 'صحة قاعدة البيانات',
      'cacheHitRates': 'معدل نجاح الكاش',
      'activeSessions': 'الجلسات النشطة',
      'serverResourceUsage': 'استخدام موارد الخادم',
      'environmentSettings': 'إعدادات البيئة',
      'paymentGateway': 'بوابة الدفع',
      'deliverySettings': 'إعدادات التوصيل',
      'emailSMSSettings': 'إعدادات البريد والرسائل',
      'storageSettings': 'إعدادات التخزين',
      'cacheSettings': 'إعدادات الكاش',
      'filterByUser': 'تصفية حسب المستخدم',
      'filterByAction': 'تصفية حسب الإجراء',
      'filterByEntity': 'تصفية حسب الكيان',
      'filterByDateRange': 'تصفية حسب التاريخ',
      'exportAuditLogs': 'تصدير سجلات المراجعة',
      'securityAlerts': 'تنبيهات الأمان',
      'crossBranchAnalytics': 'تحليلات الفروع',
      'revenueComparison': 'مقارنة الإيرادات',
      'userGrowth': 'نمو المستخدمين',
      'medicinePopularity': 'شعبية الأدوية',
      'geographicDistribution': 'التوزيع الجغرافي',
      'generateReport': 'إنشاء تقرير',
      'comparePeriods': 'مقارنة الفترات',
      'exportToPDF': 'تصدير كـ PDF',
      'exportToExcel': 'تصدير كـ Excel',
      'branchPerformance': 'أداء الفرع',
      'branchDetails': 'تفاصيل الفرع',
      'systemOverview': 'نظرة عامة على النظام',
      'userManagement': 'إدارة المستخدمين',
      'contentManagement': 'إدارة المحتوى',
      'operations': 'العمليات',
      'analyticsSection': 'التحليلات',
      'security': 'الأمان',
      'configuration': 'الإعدادات',
      'welcomeBack': 'مرحباً بعودتك',
      'loginSubtitle': 'سجّل الدخول إلى فارما وورلد الأدمن الأعلى',
      'enterMfaCode': 'أدخل رمز التحقق المكون من 6 أرقام',
      'superAdminLogin': 'تسجيل دخول الأدمن الأعلى',
      'rememberMe': 'تذكرني',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'totalRevenueAcross': 'إجمالي الإيرادات عبر جميع الصيدليات',
      'ordersSystemWide': 'إجمالي الطلبات عبر النظام',
      'allSystemUsers': 'جميع المستخدمين (عملاء، سائقون، مشرفون)',
      'medicineListings': 'قائمة الأدوية',
      'systemHealthStatus': 'حالة صحة النظام',
      'apiStatus': 'حالة API',
      'databaseStatus': 'حالة قاعدة البيانات',
      'cacheStatus': 'حالة الكاش',
      'healthy': 'سليم',
      'degraded': 'يحتاج تحسين',
      'down': 'متوقف',
      'normal': 'طبيعي',
      'high': 'مرتفع',
      'critical': 'حرج',
      'yes': 'نعم',
      'no': 'لا',
      'all': 'الكل',
      'activeFlag': 'نشط',
      'inactiveFlag': 'غير نشط',
      'addNew': 'إضافة جديد',
      'rollout': 'نشر',
      'targetedRoles': 'الأدوار المستهدفة',
      'targetedUsers': 'المستخدمون المستهدفون',
      'abTesting': 'اختبار A/B',
      'maintenanceMessage': 'رسالة الصيانة',
      'whitelistIPs': 'العناوين المسموحة',
      'whitelistUsers': 'المستخدمون المسموحون',
      'scheduledWindow': 'النافذة المجدولة',
      'currentStatus': 'الحالة الحالية',
      'permission': 'الصلاحية',
      'noRolesDefined': 'لم يتم تعريف أدوار بعد',
      'createCustomRole': 'إنشاء دور مخصص',
      'assignPermissions': 'تعيين الصلاحيات',
      'actions': 'الإجراءات',
      'role': 'الدور',
      'lastActive': 'آخر نشاط',
      'dateJoined': 'تاريخ الانضمام',
      'userDetail': 'تفاصيل المستخدم',
      'fullHistory': 'السجل الكامل',
      'responseTime': 'وقت الاستجابة',
      'uptime': 'وقت التشغيل',
      'errorRate': 'معدل الخطأ',
      'requestsPerSecond': 'طلبات/ثانية',
      'cpuUsage': 'استخدام المعالج',
      'memoryUsage': 'استخدام الذاكرة',
      'diskUsage': 'استخدام القرص',
      'connectionPool': 'مجموعة الاتصالات',
      'activeConnections': 'الاتصالات النشطة',
      'hitRate': 'معدل النجاح',
      'missRate': 'معدل الفشل',
      'totalKeys': 'إجمالي المفاتيح',
      'memoryConsumed': 'الذاكرة المستخدمة',
      'onlineSessions': 'الجلسات المتصلة',
      'peakToday': 'الذروة اليوم',
      'avgDuration': 'متوسط المدة',
      'env': 'البيئة',
      'region': 'المنطقة',
      'apiEndpoint': 'نقطة نهاية API',
      'debugMode': 'وضع التصحيح',
      'maxUploadSize': 'حجم الرفع الأقصى',
      'currency': 'العملة',
      'taxRate': 'معدل الضريبة',
      'deliveryRadius': 'نطاق التوصيل',
      'maxDeliveryDistance': 'أقصى مسافة توصيل',
      'driverCommission': 'عمولة السائق',
      'smtpHost': 'SMTP Host',
      'smtpPort': 'SMTP Port',
      'senderEmail': 'البريد المرسل',
      'smsProvider': 'مزود الرسائل',
      'firebaseConfig': 'إعدادات Firebase',
      'storageProvider': 'مزود التخزين',
      'maxFileSize': 'حجم الملف الأقصى',
      'allowedFormats': 'الصيغ المسموحة',
      'driverTTL': 'TTL السائق',
      'orderCacheTTL': 'TTL كاش الطلبات',
      'user': 'المستخدم',
      'action': 'الإجراء',
      'entity': 'الكيان',
      'timestamp': 'الوقت',
      'details': 'التفاصيل',
      'noAuditLogs': 'لا توجد سجلات مراجعة',
      'period': 'الفترة',
      'revenueByPharmacy': 'الإيرادات حسب الصيدلية',
      'ordersByCity': 'الطلبات حسب المدينة',
      'newUsersOverTime': 'المستخدمون الجدد عبر الزمن',
      'usersByRole': 'المستخدمون حسب الدور',
      'mostOrderedMedicines': 'الأدوية الأكثر طلباً',
      'ordersByMedicineType': 'الطلبات حسب نوع الدواء',
      'heatmapData': 'الخريطة الحرارية',
      'ordersByLocation': 'الطلبات حسب الموقع',
      'reportType': 'نوع التقرير',
      'dateRange': 'نطاق التاريخ',
      'startDate': 'تاريخ البداية',
      'endDate': 'تاريخ النهاية',
      'comparisonPeriod': 'فترة المقارنة',
      'downloadReport': 'تحميل التقرير',
      'branch': 'الفرع',
      'performance': 'الأداء',
      'comparisons': 'المقارنات',
    },
  };

  String translate(String key) => _localizedValues[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
