import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ar'),
  ];

  static const List<String> supportedLanguages = ['en', 'ar'];

  bool get isArabic => locale.languageCode == 'ar';
  bool get isEnglish => locale.languageCode == 'en';
  TextDirection get textDirection =>
      isArabic ? TextDirection.rtl : TextDirection.ltr;

  final Map<String, String> _en = const {
    'appName': 'PharmaWorld',
    'home': 'Home',
    'categories': 'Categories',
    'cart': 'Cart',
    'profile': 'Profile',
    'orders': 'Orders',
    'wishlist': 'Wishlist',
    'search': 'Search',
    'notifications': 'Notifications',
    'settings': 'Settings',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'forgotPassword': 'Forgot Password?',
    'resetPassword': 'Reset Password',
    'email': 'Email',
    'password': 'Password',
    'enterEmail': 'Enter your email',
    'enterPassword': 'Enter your password',
    'enterName': 'Enter your full name',
    'enterPhone': 'Enter your phone number',
    'confirmPassword': 'Confirm Password',
    'rememberMe': 'Remember me',
    'dontHaveAccount': "Don't have an account?",
    'alreadyHaveAccount': 'Already have an account?',
    'orContinueWith': 'Or continue with',
    'signInWithGoogle': 'Sign in with Google',
    'signInWithPhone': 'Sign in with Phone',
    'featuredMedicines': 'Featured Medicines',
    'popularCategories': 'Popular Categories',
    'specialOffers': 'Special Offers',
    'trendingNow': 'Trending Now',
    'viewAll': 'View All',
    'addToCart': 'Add to Cart',
    'removeFromCart': 'Remove from Cart',
    'buyNow': 'Buy Now',
    'quantity': 'Quantity',
    'price': 'Price',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'deliveryFee': 'Delivery Fee',
    'tax': 'Tax',
    'grandTotal': 'Grand Total',
    'applyCoupon': 'Apply Coupon',
    'couponCode': 'Coupon Code',
    'checkout': 'Checkout',
    'placeOrder': 'Place Order',
    'selectAddress': 'Select Address',
    'addAddress': 'Add Address',
    'selectPaymentMethod': 'Select Payment Method',
    'cashOnDelivery': 'Cash on Delivery',
    'creditCard': 'Credit Card',
    'orderSummary': 'Order Summary',
    'confirmOrder': 'Confirm Order',
    'orderPlaced': 'Order Placed Successfully',
    'orderDetails': 'Order Details',
    'pending': 'Pending',
    'confirmed': 'Confirmed',
    'processing': 'Processing',
    'outForDelivery': 'Out for Delivery',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'editProfile': 'Edit Profile',
    'changePassword': 'Change Password',
    'addresses': 'Addresses',
    'wallet': 'Wallet',
    'coupons': 'Coupons',
    'reviews': 'Reviews',
    'loyalty': 'Loyalty',
    'referral': 'Referral',
    'support': 'Support',
    'language': 'Language',
    'darkMode': 'Dark Mode',
    'about': 'About',
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'version': 'Version',
    'english': 'English',
    'arabic': 'العربية',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'retry': 'Retry',
    'loading': 'Loading...',
    'noInternet': 'No internet connection',
    'somethingWentWrong': 'Something went wrong',
    'tryAgain': 'Try Again',
    'noData': 'No data available',
    'emptyCart': 'Your cart is empty',
    'emptyWishlist': 'Your wishlist is empty',
    'emptyOrders': 'You have no orders yet',
    'goShopping': 'Go Shopping',
    'scanBarcode': 'Scan Barcode',
    'writeReview': 'Write Review',
    'submitReview': 'Submit Review',
    'customerReviews': 'Customer Reviews',
    'productDetails': 'Product Details',
    'description': 'Description',
    'relatedProducts': 'Related Products',
    'inStock': 'In Stock',
    'outOfStock': 'Out of Stock',
    'walletBalance': 'Wallet Balance',
    'topUp': 'Top Up',
    'transactionHistory': 'Transaction History',
    'pointsBalance': 'Points Balance',
    'referralCode': 'Referral Code',
    'shareReferral': 'Share Referral',
    'chatWithSupport': 'Chat with Support',
    'createTicket': 'Create Ticket',
    'sendMessage': 'Send Message',
    'name': 'Name',
    'phone': 'Phone',
    'address': 'Address',
    'city': 'City',
    'required': 'This field is required',
    'invalidEmail': 'Please enter a valid email',
    'invalidPhone': 'Please enter a valid phone number',
    'passwordTooShort': 'Password must be at least 8 characters',
    'passwordMismatch': 'Passwords do not match',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'getStarted': 'Get Started',
    'next': 'Next',
    'skip': 'Skip',
    'onboardingTitle1': 'Welcome to PharmaWorld',
    'onboardingSubtitle1': 'Your trusted online pharmacy',
    'onboardingTitle2': 'Browse & Order Medicines',
    'onboardingSubtitle2': 'Search thousands of medicines easily',
    'onboardingTitle3': 'Fast Delivery',
    'onboardingSubtitle3': 'Get your medicines delivered quickly',
    'onboardingTitle4': 'Track Your Orders',
    'onboardingSubtitle4': 'Real-time tracking for all your orders',
    'verifyEmail': 'Verify Email',
    'verifyPhone': 'Verify Phone',
    'otpVerification': 'OTP Verification',
    'resendOtp': 'Resend OTP',
    'currentPassword': 'Current Password',
    'newPassword': 'New Password',
    'recentSearches': 'Recent Searches',
    'trendingSearches': 'Trending Searches',
    'noResults': 'No results found',
    'filter': 'Filter',
    'sortBy': 'Sort By',
    'priceLowToHigh': 'Price: Low to High',
    'priceHighToLow': 'Price: High to Low',
    'newest': 'Newest',
    'popularity': 'Popularity',
    'rating': 'Rating',
    'brand': 'Brand',
    'nearbyPharmacies': 'Nearby Pharmacies',
    'reorder': 'Reorder',
    'trackOrder': 'Track Order',
    'invoice': 'Invoice',
    'returnRequest': 'Return Request',
    'notificationSettings': 'Notification Settings',
    'pushNotifications': 'Push Notifications',
    'emailNotifications': 'Email Notifications',
    'orderUpdates': 'Order Updates',
    'promotions': 'Promotions',
    'savedAddresses': 'Saved Addresses',
    'addNewAddress': 'Add New Address',
    'setDefault': 'Set as Default',
    'removeAddress': 'Remove Address',
    'topUpWallet': 'Top Up Wallet',
    'enterAmount': 'Enter amount',
    'earned': 'Earned',
    'spent': 'Spent',
    'redeemPoints': 'Redeem Points',
    'currentTier': 'Current Tier',
    'nextTier': 'Next Tier',
    'shareWithFriends': 'Share with Friends',
    'contactSupport': 'Contact Support',
    'submitTicket': 'Submit Ticket',
    'ticketSubject': 'Subject',
    'ticketMessage': 'Message',
    'aboutPharmaworld': 'About PharmaWorld',
    'contactUs': 'Contact Us',
    'followUs': 'Follow Us',
    'rateApp': 'Rate the App',
    'shareApp': 'Share the App',
    'acceptTerms': 'Accept Terms',
  };

  final Map<String, String> _ar = const {
    'appName': 'فارما وورلد',
    'home': 'الرئيسية',
    'categories': 'الأقسام',
    'cart': 'سلة التسوق',
    'profile': 'الملف الشخصي',
    'orders': 'الطلبات',
    'wishlist': 'المفضلة',
    'search': 'بحث',
    'notifications': 'الإشعارات',
    'settings': 'الإعدادات',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'logout': 'تسجيل الخروج',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'resetPassword': 'إعادة تعيين كلمة المرور',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'enterEmail': 'أدخل بريدك الإلكتروني',
    'enterPassword': 'أدخل كلمة المرور',
    'enterName': 'أدخل اسمك الكامل',
    'enterPhone': 'أدخل رقم هاتفك',
    'confirmPassword': 'تأكيد كلمة المرور',
    'rememberMe': 'تذكرني',
    'dontHaveAccount': 'ليس لديك حساب؟',
    'alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'orContinueWith': 'أو تابع باستخدام',
    'signInWithGoogle': 'تسجيل الدخول باستخدام Google',
    'signInWithPhone': 'تسجيل الدخول باستخدام الهاتف',
    'featuredMedicines': 'أدوية مميزة',
    'popularCategories': 'الأقسام الشائعة',
    'specialOffers': 'عروض خاصة',
    'trendingNow': 'الأكثر رواجاً',
    'viewAll': 'عرض الكل',
    'addToCart': 'أضف إلى السلة',
    'removeFromCart': 'إزالة من السلة',
    'buyNow': 'اشترِ الآن',
    'quantity': 'الكمية',
    'price': 'السعر',
    'total': 'الإجمالي',
    'subtotal': 'المجموع الفرعي',
    'discount': 'الخصم',
    'deliveryFee': 'رسوم التوصيل',
    'tax': 'الضريبة',
    'grandTotal': 'الإجمالي الكلي',
    'applyCoupon': 'تطبيق الكوبون',
    'couponCode': 'كود الخصم',
    'checkout': 'إتمام الطلب',
    'placeOrder': 'تأكيد الطلب',
    'selectAddress': 'اختر العنوان',
    'addAddress': 'إضافة عنوان',
    'selectPaymentMethod': 'اختر طريقة الدفع',
    'cashOnDelivery': 'الدفع عند الاستلام',
    'creditCard': 'بطاقة ائتمان',
    'orderSummary': 'ملخص الطلب',
    'confirmOrder': 'تأكيد الطلب',
    'orderPlaced': 'تم الطلب بنجاح',
    'orderDetails': 'تفاصيل الطلب',
    'pending': 'قيد الانتظار',
    'confirmed': 'تم التأكيد',
    'processing': 'قيد المعالجة',
    'outForDelivery': 'خرج للتوصيل',
    'delivered': 'تم التوصيل',
    'cancelled': 'تم الإلغاء',
    'editProfile': 'تعديل الملف الشخصي',
    'changePassword': 'تغيير كلمة المرور',
    'addresses': 'العناوين',
    'wallet': 'المحفظة',
    'coupons': 'الكوبونات',
    'reviews': 'التقييمات',
    'loyalty': 'الولاء',
    'referral': 'الإحالة',
    'support': 'الدعم',
    'language': 'اللغة',
    'darkMode': 'الوضع الداكن',
    'about': 'حول',
    'privacyPolicy': 'سياسة الخصوصية',
    'termsOfService': 'شروط الخدمة',
    'version': 'الإصدار',
    'english': 'English',
    'arabic': 'العربية',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'close': 'إغلاق',
    'retry': 'إعادة المحاولة',
    'loading': 'جاري التحميل...',
    'noInternet': 'لا يوجد اتصال بالإنترنت',
    'somethingWentWrong': 'حدث خطأ ما',
    'tryAgain': 'حاول مرة أخرى',
    'noData': 'لا توجد بيانات',
    'emptyCart': 'سلة التسوق فارغة',
    'emptyWishlist': 'المفضلة فارغة',
    'emptyOrders': 'ليس لديك طلبات بعد',
    'goShopping': 'ابدأ التسوق',
    'scanBarcode': 'مسح الباركود',
    'writeReview': 'كتابة تقييم',
    'submitReview': 'إرسال التقييم',
    'customerReviews': 'تقييمات العملاء',
    'productDetails': 'تفاصيل المنتج',
    'description': 'الوصف',
    'relatedProducts': 'منتجات ذات صلة',
    'inStock': 'متوفر',
    'outOfStock': 'غير متوفر',
    'walletBalance': 'رصيد المحفظة',
    'topUp': 'شحن المحفظة',
    'transactionHistory': 'سجل المعاملات',
    'pointsBalance': 'رصيد النقاط',
    'referralCode': 'كود الإحالة',
    'shareReferral': 'مشاركة الإحالة',
    'chatWithSupport': 'محادثة الدعم',
    'createTicket': 'إنشاء تذكرة',
    'sendMessage': 'إرسال رسالة',
    'name': 'الاسم',
    'phone': 'الهاتف',
    'address': 'العنوان',
    'city': 'المدينة',
    'required': 'هذا الحقل مطلوب',
    'invalidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
    'invalidPhone': 'يرجى إدخال رقم هاتف صحيح',
    'passwordTooShort': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'passwordMismatch': 'كلمتا المرور غير متطابقتين',
    'error': 'خطأ',
    'success': 'نجاح',
    'warning': 'تحذير',
    'getStarted': 'ابدأ الآن',
    'next': 'التالي',
    'skip': 'تخطي',
    'onboardingTitle1': 'مرحباً بك في فارما وورلد',
    'onboardingSubtitle1': 'صيدليتك الموثوقة عبر الإنترنت',
    'onboardingTitle2': 'تصفح واطلب الأدوية',
    'onboardingSubtitle2': 'ابحث عن آلاف الأدوية بسهولة',
    'onboardingTitle3': 'توصيل سريع',
    'onboardingSubtitle3': 'احصل على أدويةك بسرعة',
    'onboardingTitle4': 'تتبع طلباتك',
    'onboardingSubtitle4': 'تتبع مباشر لجميع طلباتك',
    'verifyEmail': 'تأكيد البريد الإلكتروني',
    'verifyPhone': 'تأكيد رقم الهاتف',
    'otpVerification': 'تحقق من رمز التأكيد',
    'resendOtp': 'إعادة إرسال الرمز',
    'currentPassword': 'كلمة المرور الحالية',
    'newPassword': 'كلمة المرور الجديدة',
    'recentSearches': 'عمليات البحث الأخيرة',
    'trendingSearches': 'البحث الشائع',
    'noResults': 'لم يتم العثور على نتائج',
    'filter': 'تصفية',
    'sortBy': 'ترتيب حسب',
    'priceLowToHigh': 'السعر: من الأقل إلى الأعلى',
    'priceHighToLow': 'السعر: من الأعلى إلى الأقل',
    'newest': 'الأحدث',
    'popularity': 'الأكثر شعبية',
    'rating': 'التقييم',
    'brand': 'العلامة التجارية',
    'nearbyPharmacies': 'الصيدليات القريبة',
    'reorder': 'إعادة الطلب',
    'trackOrder': 'تتبع الطلب',
    'invoice': 'الفاتورة',
    'returnRequest': 'طلب إرجاع',
    'notificationSettings': 'إعدادات الإشعارات',
    'pushNotifications': 'إشعارات الدفع',
    'emailNotifications': 'إشعارات البريد الإلكتروني',
    'orderUpdates': 'تحديثات الطلب',
    'promotions': 'العروض الترويجية',
    'savedAddresses': 'العناوين المحفوظة',
    'addNewAddress': 'إضافة عنوان جديد',
    'setDefault': 'تعيين كافتراضي',
    'removeAddress': 'إزالة العنوان',
    'topUpWallet': 'شحن المحفظة',
    'enterAmount': 'أدخل المبلغ',
    'earned': 'تم كسبه',
    'spent': 'تم إنفاقه',
    'redeemPoints': 'استبدال النقاط',
    'currentTier': 'المستوى الحالي',
    'nextTier': 'المستوى التالي',
    'shareWithFriends': 'شارك مع الأصدقاء',
    'contactSupport': 'تواصل مع الدعم',
    'submitTicket': 'إرسال تذكرة',
    'ticketSubject': 'الموضوع',
    'ticketMessage': 'الرسالة',
    'aboutPharmaworld': 'حول فارما وورلد',
    'contactUs': 'تواصل معنا',
    'followUs': 'تابعنا',
    'rateApp': 'قيّم التطبيق',
    'shareApp': 'شارك التطبيق',
    'acceptTerms': 'قبول الشروط',
  };

  String translate(String key) {
    final currentLocale = locale.languageCode == 'ar' ? _ar : _en;
    return currentLocale[key] ?? key;
  }

  String operator [](String key) => translate(key);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
